### ISSUE TITLE
Issues rendering arabic text

### ISSUE THREAD

**Issue by Yummy-Pizza** [dfyz/osm-renderer#12]
Hi, it seems that the server can't render Arabic text and instead replaces the names with square characters (□). How can this be fixed? I've tried installing an Arabic font on the system but the results were still the same.

**Comment by dfyz** [comment]
This is an unfortunate side-effect of implementing bespoke text rendering in order to make the resulting binary self-contained. I bundle [Noto Sans](https://github.com/dfyz/osm-renderer/blob/master/src/draw/font/NotoSans-Regular.ttf) (so system fonts are not used at all), which only supports Latin, Greek, and Cyrillic scripts. I could bundle additional fonts for other scripts, but I think properly rendering Arabic is outside the scope of this project: at the very least, it's right-to-left instead of left-to-right, so I'd need to implement [Unicode Bidirectional Algorithm](https://unicode.org/reports/tr9/) to account for this.

I will update the README to clarify that only a limited number of scripts are supported.
