### ISSUE TITLE
panic on invalid multipolygon pbf

### ISSUE THREAD

**Issue by cdbattags** [dfyz/osm-renderer#2]
```
Relation #83533 is not a valid multipolygon (built 0 complete rings, but 1417 segments are unmatched)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/geodata/importer.rs:142:103
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /Users/cdbattags/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: renderer::geodata::importer::parse_pbf::{{closure}}
             at ./src/geodata/importer.rs:142:40
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /Users/cdbattags/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:269:13
   6: osmpbf::block::PrimitiveBlock::for_each_element
             at /Users/cdbattags/.cargo/registry/src/github.com-1ecc6299db9ec823/osmpbf-0.2.5/src/block.rs:69:17
   7: osmpbf::reader::ElementReader<R>::for_each
             at /Users/cdbattags/.cargo/registry/src/github.com-1ecc6299db9ec823/osmpbf-0.2.5/src/reader.rs:76:21
   8: renderer::geodata::importer::parse_pbf
             at ./src/geodata/importer.rs:99:5
   9: renderer::geodata::importer::import
             at ./src/geodata/importer.rs:30:24
  10: importer::main
             at ./src/bin/importer.rs:17:11
  11: core::ops::function::FnOnce::call_once
             at /Users/cdbattags/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

File I was working with can be downloaded here: https://download.geofabrik.de/north-america/us/georgia-latest.osm.pbf

Let me know if you need any more help reproducing. Thanks!

**Comment by cdbattags** [comment]
Looks like maybe need to add a new match on throwing out segments that don't complete a ring?

**Comment by cdbattags** [comment]
It also panics with Hawaii if you'd like to try a smaller data set!

**Comment by dfyz** [comment]
Thanks for the report! For some reason, the Geofabrik file for Hawaii includes the [whole of the US](https://www.openstreetmap.org/relation/148838) as a relation, which, not surprisingly, references ways from other states that are not present in the file.

The old OSM parser handled this just fine, but the new PBF one didn't. I just pushed a fix, which apparently fixed parsing for Georgia, too.

After the fix, I can import and render all of Georgia (albeit quite slowly) on my laptop. However, there's something subtly wrong with Hawaii even after the fix (unrelated to the original issue), because the importer runs out of memory for me even though I have 24 GB of RAM. These islands look very peculiar on the map, so I suspect the importer is hitting some edge case I didn't missed in my tests. Unfortunately, I don't have much time to investigate now.

Feel free to open another issue if Hawaii are important to you, though. :)
